-- Generated by npm run backend:prepare. Applies only missing schema stages.
-- No catalog reset, no automatic admin claim, no credentials.
begin;
do $stage$ begin if to_regclass('public.products') is null then execute $migration$
-- Run once in the Supabase SQL editor, or deploy with `supabase db push`.
create table public.products (
  id text primary key,
  name text not null check (length(name) between 1 and 300),
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  category text not null,
  product_group text not null default 'home' check (product_group in ('home','offer','choice','recommendation','unavailable')),
  image_url text check (image_url is null or image_url like 'https://res.cloudinary.com/%'),
  details jsonb not null default '{}' check (jsonb_typeof(details) = 'object'),
  sort_order integer not null default 0,
  active boolean not null default true
);
alter table public.products enable row level security;
create policy "Public active catalog" on public.products for select to anon, authenticated using (active);
revoke all on public.products from anon, authenticated;
grant select on public.products to anon, authenticated;

create table public.customer_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}' check (
    jsonb_typeof(data) = 'object' and not (data ? 'orders') and octet_length(data::text) <= 150000
  )
);
alter table public.customer_state enable row level security;
create policy "Read own state" on public.customer_state for select to authenticated using ((select auth.uid()) = user_id);
create policy "Create own state" on public.customer_state for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Update own state" on public.customer_state for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
revoke all on public.customer_state from anon, authenticated;
grant select, insert, update on public.customer_state to authenticated;

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id),
  request_id text not null,
  created_at timestamptz not null default now(),
  document jsonb not null,
  unique(user_id, request_id)
);
create index orders_customer_date on public.orders(user_id, created_at desc);
alter table public.orders enable row level security;
create policy "Read own orders" on public.orders for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.orders from anon, authenticated;
grant select on public.orders to authenticated;

create function public.place_order(p_items jsonb, p_profile jsonb, p_voucher text, p_request_id text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  customer uuid := auth.uid();
  result jsonb;
  line jsonb;
  product public.products%rowtype;
  quantity integer;
  lines jsonb := '[]';
  subtotal numeric := 0;
  discount numeric := 0;
  order_id uuid := gen_random_uuid();
begin
  if customer is null then raise exception 'Sign in before placing an order.'; end if;
  if p_request_id is null or length(p_request_id) not between 8 and 150 then raise exception 'Invalid checkout request.'; end if;
  -- Same request after a timeout returns the existing order, without charging stock twice.
  perform pg_advisory_xact_lock(hashtextextended(customer::text || ':' || p_request_id, 0));
  select document into result from public.orders where user_id = customer and request_id = p_request_id;
  if found then return result; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then raise exception 'Select items to order.'; end if;
  if jsonb_array_length(p_items) not between 1 and 100 then raise exception 'Choose between 1 and 100 products.'; end if;
  if p_profile is null or jsonb_typeof(p_profile) <> 'object'
    or coalesce(length(trim(p_profile->>'name')), 0) not between 2 and 150
    or coalesce(length(trim(p_profile->>'address')), 0) not between 8 and 1000
    or coalesce(p_profile->>'phone', '') !~ '^\+?[0-9 -]+$'
    or length(regexp_replace(coalesce(p_profile->>'phone',''), '[^0-9]', '', 'g')) not between 7 and 15
    then raise exception 'Enter a valid name, phone number and delivery address.'; end if;
  if (select count(distinct value->>'productId') from jsonb_array_elements(p_items)) <> jsonb_array_length(p_items)
    then raise exception 'Duplicate or missing products in checkout.'; end if;
  if trim(coalesce(p_voucher, '')) <> '' and upper(trim(p_voucher)) <> 'GULMELI10'
    then raise exception 'Voucher is not recognized.'; end if;
  -- Lock products in a consistent order. Any failure rolls the whole transaction back.
  for line in select value from jsonb_array_elements(p_items) order by value->>'productId' loop
    if jsonb_typeof(line->'quantity') is distinct from 'number' or (line->>'quantity') !~ '^[0-9]{1,4}$'
      then raise exception 'Invalid item quantity.'; end if;
    quantity := (line->>'quantity')::integer;
    if quantity < 1 then raise exception 'Invalid item quantity.'; end if;
    select * into product from public.products where id = line->>'productId' and active for update;
    if not found then raise exception 'A product is no longer available.'; end if;
    if product.stock < quantity then raise exception 'Not enough stock for %. Refresh your cart.', product.name; end if;
    update public.products set stock = stock - quantity where id = product.id;
    lines := lines || jsonb_build_array(jsonb_build_object('productId',product.id,'name',product.name,'quantity',quantity,'price',product.price));
    subtotal := subtotal + product.price * quantity;
  end loop;
  if upper(trim(p_voucher)) = 'GULMELI10' and subtotal >= 500 then discount := least(100, round(subtotal * 0.1)); end if;
  result := jsonb_build_object('id',order_id,'createdAt',now(),'items',lines,'subtotal',subtotal,'discount',discount,'total',subtotal-discount,
    'profile',jsonb_build_object('name',trim(p_profile->>'name'),'phone',trim(p_profile->>'phone'),'address',trim(p_profile->>'address'),'avatar',''),
    'status','Placed');
  insert into public.orders(id,user_id,request_id,document) values (order_id,customer,p_request_id,result);
  return result;
end $$;
revoke all on function public.place_order(jsonb,jsonb,text,text) from public, anon;
grant execute on function public.place_order(jsonb,jsonb,text,text) to authenticated;

create function public.cancel_order(p_order_id uuid) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare result jsonb; line jsonb;
begin
  if auth.uid() is null then raise exception 'Sign in first.'; end if;
  select document into result from public.orders where id = p_order_id and user_id = auth.uid() for update;
  if not found then raise exception 'Order not found.'; end if;
  if result->>'status' = 'Cancelled' then return result; end if;
  if result->>'status' <> 'Placed' then raise exception 'This order can no longer be cancelled. Contact the store.'; end if;
  for line in select value from jsonb_array_elements(result->'items') order by value->>'productId' loop
    update public.products set stock = stock + (line->>'quantity')::integer where id = line->>'productId';
  end loop;
  result := jsonb_set(result, '{status}', '"Cancelled"');
  update public.orders set document = result where id = p_order_id;
  return result;
end $$;
revoke all on function public.cancel_order(uuid) from public, anon;
grant execute on function public.cancel_order(uuid) to authenticated;

-- Durable per-account rate limit for the authenticated image proxy.
create table public.image_upload_limits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  window_start timestamptz not null,
  attempts integer not null
);
alter table public.image_upload_limits enable row level security;
revoke all on public.image_upload_limits from anon, authenticated;
create function public.reserve_image_upload() returns boolean
language plpgsql security definer set search_path = '' as $$
declare row public.image_upload_limits%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in first.'; end if;
  insert into public.image_upload_limits values (auth.uid(),now(),0) on conflict do nothing;
  select * into row from public.image_upload_limits where user_id = auth.uid() for update;
  if row.window_start < now() - interval '1 hour' then
    update public.image_upload_limits set window_start = now(), attempts = 1 where user_id = auth.uid();
    return true;
  end if;
  if row.attempts >= 10 then return false; end if;
  update public.image_upload_limits set attempts = attempts + 1 where user_id = auth.uid();
  return true;
end $$;
revoke all on function public.reserve_image_upload() from public, anon;
grant execute on function public.reserve_image_upload() to authenticated;

$migration$; end if; end $stage$;
do $stage$ begin if to_regclass('public.admin_members') is null then execute $migration$
-- Shared storefront configuration and the admin role that may change it.
-- Apply after 202609130001_store.sql.

-- Who is allowed to run the dashboard against this project.
create table public.admin_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'manager'
    check (role in ('super_admin','manager','product_manager','order_manager','support','marketing','accountant','warehouse')),
  created_at timestamptz not null default now()
);
alter table public.admin_members enable row level security;
revoke all on public.admin_members from anon, authenticated;
grant select on public.admin_members to authenticated;
create policy "Read own membership" on public.admin_members
  for select to authenticated using ((select auth.uid()) = user_id);

-- Kept out of the policies below so they never recurse through RLS.
create function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.admin_members where user_id = auth.uid())
$$;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

create function public.is_super_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.admin_members where user_id = auth.uid() and role = 'super_admin'
  )
$$;
revoke all on function public.is_super_admin() from public, anon;
grant execute on function public.is_super_admin() to authenticated;

-- The published storefront configuration. One row, readable by everyone, so
-- colours, wording, menus, feature switches and contact details can change
-- without shipping a new build of the app.
create table public.app_config (
  id text primary key default 'storefront' check (id = 'storefront'),
  published jsonb not null default '{}' check (
    jsonb_typeof(published) = 'object' and octet_length(published::text) <= 400000
  ),
  published_at timestamptz not null default now(),
  published_by uuid references auth.users(id)
);
alter table public.app_config enable row level security;
revoke all on public.app_config from anon, authenticated;
grant select on public.app_config to anon, authenticated;
grant insert, update on public.app_config to authenticated;
create policy "Anyone may read the published configuration" on public.app_config
  for select to anon, authenticated using (true);
create policy "Admins may create the configuration" on public.app_config
  for insert to authenticated with check ((select public.is_admin()));
create policy "Admins may publish the configuration" on public.app_config
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

-- Every published version, so a bad change can be rolled back.
create table public.app_config_versions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  actor uuid references auth.users(id),
  label text not null default '',
  changed_paths text[] not null default '{}',
  config jsonb not null
);
create index app_config_versions_recent on public.app_config_versions(created_at desc);
alter table public.app_config_versions enable row level security;
revoke all on public.app_config_versions from anon, authenticated;
grant select, insert on public.app_config_versions to authenticated;
create policy "Admins read configuration history" on public.app_config_versions
  for select to authenticated using ((select public.is_admin()));
create policy "Admins record configuration history" on public.app_config_versions
  for insert to authenticated with check ((select public.is_admin()));

-- Keeps a version whenever the published document actually changes.
create function public.record_config_version() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'UPDATE' and old.published is not distinct from new.published then
    return new;
  end if;
  insert into public.app_config_versions(actor, label, config)
  values (auth.uid(), 'Published from the admin dashboard', new.published);
  delete from public.app_config_versions
  where id in (
    select id from public.app_config_versions order by created_at desc offset 50
  );
  return new;
end $$;
create trigger app_config_versioned
  after insert or update on public.app_config
  for each row execute function public.record_config_version();

-- Admin writes to the catalogue. Customers keep read-only access to active
-- products through the policy in the first migration.
grant insert, update, delete on public.products to authenticated;
create policy "Admins read every product" on public.products
  for select to authenticated using ((select public.is_admin()));
create policy "Admins create products" on public.products
  for insert to authenticated with check ((select public.is_admin()));
create policy "Admins update products" on public.products
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins delete products" on public.products
  for delete to authenticated using ((select public.is_super_admin()));

-- Admins need to see and progress every order, not only their own.
create policy "Admins read every order" on public.orders
  for select to authenticated using ((select public.is_admin()));
grant update on public.orders to authenticated;
create policy "Admins update orders" on public.orders
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

-- Server-side record of who changed what, so the trail survives a device wipe.
create table public.admin_audit (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  actor uuid references auth.users(id),
  actor_name text not null default '',
  action text not null,
  resource text not null,
  record_id text,
  record_label text not null default '',
  changes jsonb not null default '[]'
);
create index admin_audit_recent on public.admin_audit(created_at desc);
alter table public.admin_audit enable row level security;
revoke all on public.admin_audit from anon, authenticated;
grant select, insert on public.admin_audit to authenticated;
create policy "Admins read the audit trail" on public.admin_audit
  for select to authenticated using ((select public.is_admin()));
create policy "Admins append to the audit trail" on public.admin_audit
  for insert to authenticated with check ((select public.is_admin()) and actor = (select auth.uid()));

$migration$; end if; end $stage$;
do $stage$ begin if to_regclass('public.admin_data') is null then execute $migration$
-- Media library, shared admin data and realtime fan-out.
-- Apply after 202609130001_store.sql and 202609140001_admin_config.sql.
-- Run the whole file once in the Supabase SQL Editor.

-- All media in the app (product photos, banners, icons, documents) lives in
-- Cloudinary; this table is the searchable index of what was stored there.
create table public.media (
  id text primary key,
  public_id text unique,
  url text not null check (url like 'https://%'),
  name text not null check (length(name) between 1 and 300),
  folder text not null default 'General',
  kind text not null default 'image'
    check (kind in ('image','video','pdf','document')),
  alt text not null default '',
  tags jsonb not null default '[]'::jsonb check (jsonb_typeof(tags) = 'array'),
  product_id text references public.products(id) on delete set null,
  width integer not null default 0,
  height integer not null default 0,
  bytes integer not null default 0,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index media_product on public.media(product_id);
create index media_recent on public.media(created_at desc);
alter table public.media enable row level security;
revoke all on public.media from anon, authenticated;
grant select on public.media to anon, authenticated;
grant insert, update, delete on public.media to authenticated;
create policy "Anyone may read media" on public.media
  for select to anon, authenticated using (true);
create policy "Admins add media" on public.media
  for insert to authenticated with check ((select public.is_admin()));
create policy "Admins update media" on public.media
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins delete media" on public.media
  for delete to authenticated using ((select public.is_admin()));

-- One row per record of every admin dashboard collection (products, orders,
-- banners, coupons, customers, pages, ...). The dashboard mirrors writes here
-- and every device receives updates through realtime, so admin CRUD in one
-- place is visible everywhere within seconds.
create table public.admin_data (
  collection text not null,
  id text not null,
  document jsonb not null check (
    jsonb_typeof(document) = 'object' and octet_length(document::text) <= 262144
  ),
  actor text not null default '',
  updated_at timestamptz not null default now(),
  primary key (collection, id)
);
create index admin_data_collection on public.admin_data(collection);
alter table public.admin_data enable row level security;
revoke all on public.admin_data from anon;
grant select, insert, update, delete on public.admin_data to authenticated;
create policy "Admins read shared records" on public.admin_data
  for select to authenticated using ((select public.is_admin()));
create policy "Admins write shared records" on public.admin_data
  for insert to authenticated with check ((select public.is_admin()));
create policy "Admins update shared records" on public.admin_data
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins delete shared records" on public.admin_data
  for delete to authenticated using ((select public.is_admin()));

-- Media uploads from the dashboard are larger and more frequent than avatar
-- uploads; raise the per-account hour limit.
create or replace function public.reserve_image_upload() returns boolean
language plpgsql security definer set search_path = '' as $$
declare row public.image_upload_limits%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in first.'; end if;
  insert into public.image_upload_limits values (auth.uid(),now(),0) on conflict do nothing;
  select * into row from public.image_upload_limits where user_id = auth.uid() for update;
  if row.window_start < now() - interval '1 hour' then
    update public.image_upload_limits set window_start = now(), attempts = 1 where user_id = auth.uid();
    return true;
  end if;
  if row.attempts >= 200 then return false; end if;
  update public.image_upload_limits set attempts = attempts + 1 where user_id = auth.uid();
  return true;
end $$;

-- First signed-in user to claim the dashboard becomes super admin; after that
-- membership is fixed by adding rows to admin_members in the Table Editor.
create or replace function public.claim_first_admin() returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null then return false; end if;
  if not exists (select 1 from public.admin_members) then
    insert into public.admin_members(user_id, role) values (auth.uid(), 'super_admin');
    return true;
  end if;
  return (select public.is_admin());
end $$;
revoke all on function public.claim_first_admin() from public, anon;
grant execute on function public.claim_first_admin() to authenticated;

-- Push changes to connected clients immediately instead of waiting for a poll.
do $$ begin
  alter publication supabase_realtime add table products;
exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table media;
exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table admin_data;
exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table orders;
exception when duplicate_object then null; when undefined_object then null; end $$;

$migration$; end if; end $stage$;
do $stage$ begin if to_regclass('public.device_tokens') is null then execute $migration$
-- Push device tokens registered by the mobile app (expo-notifications).
create table if not exists public.device_tokens (
  token text primary key,
  user_id uuid references auth.users(id) on delete set null,
  platform text not null default 'android',
  install_id text,
  created_at timestamptz not null default now()
);
alter table public.device_tokens enable row level security;
create policy "Register own device" on public.device_tokens for insert to authenticated with check ((select auth.uid()) = user_id or user_id is null);
create policy "Update own device" on public.device_tokens for update to authenticated using (user_id = (select auth.uid()) or user_id is null) with check (user_id = (select auth.uid()) or user_id is null);
create policy "Read own devices" on public.device_tokens for select to authenticated using ((select auth.uid()) = user_id);
grant select, insert, update on public.device_tokens to authenticated;

$migration$; end if; end $stage$;
do $stage$ begin if to_regprocedure('public.save_admin_changes(jsonb)') is null then execute $migration$
-- Atomic admin writes, server-owned catalog projection, safe admin enrollment.

create or replace function public.claim_first_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_admin()
$$;

-- Every device submits only changed records with the version it actually read.
create or replace function public.save_admin_changes(p_changes jsonb) returns void
language plpgsql security definer set search_path = '' as $$
declare change jsonb; existing jsonb; next_doc jsonb;
begin
  if not public.is_admin() then raise exception 'Store admin access required.'; end if;
  if jsonb_typeof(p_changes) <> 'array' or jsonb_array_length(p_changes) > 2000 then
    raise exception 'Invalid change batch.';
  end if;
  perform pg_advisory_xact_lock(15092026);
  for change in select value from jsonb_array_elements(p_changes) loop
    if coalesce(change->>'collection','') = '' or coalesce(change->>'id','') = '' then
      raise exception 'Collection and record id are required.';
    end if;
    select document into existing from public.admin_data
      where collection = change->>'collection' and id = change->>'id' for update;
    next_doc := nullif(change->'after','null'::jsonb);
    if existing is not distinct from next_doc then continue; end if;
    if existing is distinct from nullif(change->'before','null'::jsonb) then
      raise exception 'This record changed on another device. Reload before editing: % / %', change->>'collection', change->>'id';
    end if;
    if next_doc is null then
      delete from public.admin_data where collection = change->>'collection' and id = change->>'id';
    else
      if next_doc->>'id' is distinct from change->>'id' then raise exception 'Record id mismatch.'; end if;
      insert into public.admin_data(collection,id,document,actor,updated_at)
        values (change->>'collection',change->>'id',next_doc,auth.uid()::text,now())
      on conflict (collection,id) do update set document=excluded.document,actor=excluded.actor,updated_at=now();
    end if;
  end loop;
end $$;
revoke all on function public.save_admin_changes(jsonb) from public, anon;
grant execute on function public.save_admin_changes(jsonb) to authenticated;
-- Force app writes through the atomic RPC. Old builds must not bypass conflict
-- checks, overwrite stock, or edit an order without inventory reconciliation.
revoke insert,update,delete on public.admin_data,public.products,public.media from authenticated;
revoke update on public.orders from authenticated;

create or replace function public.project_admin_record() returns trigger
language plpgsql security definer set search_path = '' as $$
declare d jsonb; prev jsonb; c text; rid text; photo text; cat text; amount numeric; delta integer;
  live_order public.orders%rowtype; target_status text; item jsonb;
begin
  if tg_op = 'DELETE' then d:=old.document; c:=old.collection; rid:=old.id;
  else d:=new.document; c:=new.collection; rid:=new.id; end if;
  if tg_op = 'UPDATE' then prev:=old.document; else prev:='{}'; end if;
  -- Nested product records are inventory acknowledgements from the server.
  if c='products' and pg_trigger_depth()>1 then return new; end if;
  if c = 'products' then
    if tg_op = 'DELETE' or nullif(d->>'deletedAt','') is not null then
      update public.products set active=false where id=rid;
    else
      select value #>> '{}' into photo from jsonb_array_elements(coalesce(d->'images','[]'))
        where value #>> '{}' like 'https://%' limit 1;
      select document->>'name' into cat from public.admin_data where collection='categories' and id=d->>'categoryId';
      amount:=coalesce(nullif(d->>'salePrice','')::numeric,nullif(d->>'price','')::numeric,0);
      delta:=case when coalesce((d->>'unlimitedStock')::boolean,false) then 99 else coalesce((d->>'stock')::integer,0) end;
      insert into public.products(id,name,price,stock,category,product_group,image_url,details,active)
        values(rid,coalesce(nullif(d->>'name',''),'Unnamed product'),amount,greatest(0,delta),
          coalesce(cat,nullif(d->>'categoryName',''),'General'),
          case when d->>'storefrontGroup' in ('home','offer','choice','recommendation','unavailable') then d->>'storefrontGroup' else 'home' end,
          photo, coalesce(d->'details','{}') || jsonb_build_object('description',d->>'description','brand',d->>'brand','images',coalesce(d->'images','[]')),
          d->>'status'='published')
      on conflict (id) do update set name=excluded.name,price=excluded.price,category=excluded.category,
        product_group=excluded.product_group, image_url=case when d ? 'images' then excluded.image_url else products.image_url end,
        details=products.details || excluded.details,active=excluded.active,
        stock=case when tg_op='UPDATE' then greatest(0,products.stock + delta -
          case when coalesce((prev->>'unlimitedStock')::boolean,false) then 99 else coalesce((prev->>'stock')::integer,0) end)
          else products.stock end;
    end if;
  elsif c='categories' and tg_op <> 'DELETE' then
    update public.products p set category=d->>'name' from public.admin_data a
      where a.collection='products' and a.document->>'categoryId'=rid and p.id=a.id;
  elsif c='media' then
    if tg_op='DELETE' or nullif(d->>'deletedAt','') is not null then
      delete from public.media where id=rid;
    elsif d->>'url' like 'https://%' then
      insert into public.media(id,public_id,url,name,folder,kind,alt,tags,width,height,bytes,note)
      values(rid,nullif(d->>'publicId',''),d->>'url',coalesce(nullif(d->>'name',''),'Photo'),coalesce(d->>'folder','General'),
        coalesce(d->>'kind','image'),coalesce(d->>'alt',''),coalesce(d->'tags','[]'),
        coalesce((d->>'width')::integer,0),coalesce((d->>'height')::integer,0),
        coalesce((d->>'sizeKb')::numeric,0)*1024,coalesce(d->>'note',''))
      on conflict(id) do update set public_id=excluded.public_id,url=excluded.url,name=excluded.name,folder=excluded.folder,
        kind=excluded.kind,alt=excluded.alt,tags=excluded.tags,width=excluded.width,height=excluded.height,bytes=excluded.bytes,note=excluded.note,updated_at=now();
    end if;
  elsif c='orders' and tg_op='UPDATE' and d->>'source'='customer-app' and d->>'status' is distinct from prev->>'status' then
    select * into live_order from public.orders where id::text=rid for update;
    if found then
      target_status:=case lower(d->>'status') when 'cancelled' then 'Cancelled' when 'shipped' then 'Shipped'
        when 'delivered' then 'Delivered' when 'pending' then 'Placed' else initcap(d->>'status') end;
      if live_order.document->>'status' in ('Cancelled','Delivered') and target_status<>live_order.document->>'status' then
        raise exception 'A completed or cancelled order cannot be reopened.';
      end if;
      if target_status='Cancelled' and live_order.document->>'status'<>'Cancelled' then
        if live_order.document->>'status' in ('Shipped','Delivered') then raise exception 'Shipped orders require a return.'; end if;
        for item in select value from jsonb_array_elements(live_order.document->'items') order by value->>'productId' loop
          update public.products set stock=stock+(item->>'quantity')::integer where id=item->>'productId';
          update public.admin_data a set document=a.document || jsonb_build_object(
            'stock',p.stock,'updatedAt',now(),'revision',coalesce((a.document->>'revision')::int,0)+1),updated_at=now()
            from public.products p where a.collection='products' and a.id=p.id and p.id=item->>'productId';
        end loop;
      end if;
      update public.orders set document=jsonb_set(document,'{status}',to_jsonb(target_status)) where id=live_order.id;
    end if;
  end if;
  insert into public.admin_audit(actor,action,resource,record_id) values(auth.uid(),lower(tg_op),c,rid);
  if tg_op='DELETE' then return old; end if; return new;
end $$;
create trigger admin_record_projected after insert or update or delete on public.admin_data
  for each row execute function public.project_admin_record();

-- Customer purchases/cancellations acknowledge actual stock in the dashboard.
-- Writes originating in the admin projection are already represented there.
create or replace function public.project_inventory_count() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.admin_data set document=document || jsonb_build_object(
    'stock',new.stock,'updatedAt',now(),'revision',coalesce((document->>'revision')::int,0)+1),updated_at=now()
    where collection='products' and id=new.id and (document->>'stock')::integer is distinct from new.stock;
  return new;
end $$;
create trigger inventory_count_projected after update of stock on public.products
  for each row when (pg_trigger_depth()=0 and old.stock is distinct from new.stock)
  execute function public.project_inventory_count();

-- Durable customer/admin shared records, created on the server even with no dashboard open.
create or replace function public.project_customer_record() returns trigger
language plpgsql security definer set search_path = '' as $$
declare doc jsonb; profile jsonb; rid text;
begin
  if tg_table_name='orders' then
    rid:=new.id::text; profile:=new.document->'profile';
    doc:=jsonb_build_object('id',rid,'source','customer-app','number','APP-'||upper(left(rid,8)),
      'customerId',new.user_id,'customerName',profile->>'name','customerEmail','','guest',false,
      'status',case new.document->>'status' when 'Placed' then 'pending' else lower(new.document->>'status') end,
      'paymentStatus','unpaid','paymentMethod','Cash on delivery','subtotal',new.document->'subtotal',
      'discountTotal',new.document->'discount','shippingTotal',coalesce(new.document->'shipping','0'),
      'taxTotal',0,'refundedTotal',0,'total',new.document->'total','shippingAddress',jsonb_build_object('line1',profile->>'address'),
      'billingAddress','{}'::jsonb,'placedAt',new.created_at,'createdAt',new.created_at,'updatedAt',now(),
      'channel','app','deletedAt',null,'revision',1,'timeline','[]'::jsonb,
      'lines',(select coalesce(jsonb_agg(jsonb_build_object('productId',i->>'productId','name',i->>'name','quantity',i->'quantity',
        'unitPrice',i->'price','costPrice',0,'discount',0,'tax',0,'sku','')),'[]') from jsonb_array_elements(new.document->'items') i));
    insert into public.admin_data(collection,id,document) values('orders',rid,doc)
      on conflict(collection,id) do update set document=admin_data.document || jsonb_build_object(
        'status',doc->'status','updatedAt',now(),'revision',coalesce((admin_data.document->>'revision')::int,0)+1),updated_at=now();
  else
    rid:=new.user_id::text; profile:=new.data->'profile';
    doc:=jsonb_build_object('id',rid,'source','customer-app','name',coalesce(profile->>'name','Customer'),
      'phone',profile->>'phone','address',profile->>'address','avatar',profile->>'avatar',
      'status','active','createdAt',now(),'updatedAt',now(),'deletedAt',null,'revision',1);
    insert into public.admin_data(collection,id,document) values('customers',rid,doc)
      on conflict(collection,id) do update set document=admin_data.document || doc || jsonb_build_object(
        'createdAt',admin_data.document->'createdAt','revision',coalesce((admin_data.document->>'revision')::int,0)+1),updated_at=now();
  end if;
  return new;
end $$;
-- Avoid recursion when the admin projection updates an order.
create trigger customer_order_projected after insert or update on public.orders
  for each row when (pg_trigger_depth() = 0) execute function public.project_customer_record();
create trigger customer_profile_projected after insert or update on public.customer_state
  for each row execute function public.project_customer_record();

-- Enable all streams that clients subscribe to, including settings and accounts.
do $$ declare t text; begin
  foreach t in array array['products','media','admin_data','orders','customer_state','app_config'] loop
    begin execute format('alter publication supabase_realtime add table public.%I',t);
    exception when duplicate_object or undefined_object then null; end;
  end loop;
end $$;
alter table public.admin_data replica identity full;

-- Public presentation fields only. Internal admin notes and private collections
-- must never be exposed through the storefront API.
create or replace function public.storefront_content() returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object('collection',collection,'id',id,'document',(
    select coalesce(jsonb_object_agg(key,value),'{}') from jsonb_each(document)
    where key=any(array['id','name','title','heading','subheading','image','mobileImage','featuredImage','logo','icon',
      'backgroundColor','ctaLabel','ctaLink','categoryId','productId','productIds','placement','devices','sortOrder',
      'slug','description','body','content','question','answer','status','publishAt','unpublishAt'])
  )) order by coalesce((document->>'sortOrder')::numeric,0),id),'[]')
  from public.admin_data
  where collection in ('banners','categories','collections','pages','faqs','menus')
    and nullif(document->>'deletedAt','') is null
    and document->>'status' in ('published','active')
    and (nullif(document->>'publishAt','') is null or (document->>'publishAt')::timestamptz<=now())
    and (nullif(document->>'unpublishAt','') is null or (document->>'unpublishAt')::timestamptz>now())
$$;
revoke all on function public.storefront_content() from public;
grant execute on function public.storefront_content() to anon,authenticated;

-- Adopt the existing live catalog without manufacturing demo sales/customers.
insert into public.admin_data(collection,id,document)
select 'products',id,jsonb_build_object('id',id,'name',name,'slug',id,'sku',upper(id),'price',price,'stock',stock,
  'status',case when active then 'published' else 'draft' end,'categoryName',category,
  'storefrontGroup',product_group,'images',case when image_url is null then '[]'::jsonb else jsonb_build_array(image_url) end,
  'details',details,'createdAt',now(),'updatedAt',now(),'revision',1,'deletedAt',null)
from public.products on conflict do nothing;
-- Hydrate the dashboard with historical customer data as well as future events.
update public.orders set document=document;
update public.customer_state set data=data;

$migration$; end if; end $stage$;
do $stage$ begin if to_regprocedure('public.quote_order(jsonb,text)') is null then execute $migration$
-- Quotes and checkout read the same live shipping, order limits and coupon rules.
create or replace function public.quote_order(p_items jsonb,p_voucher text default '') returns jsonb
language plpgsql security definer set search_path = '' as $$
declare config jsonb; coupon jsonb; line jsonb; p public.products%rowtype; quantity integer;
  subtotal numeric:=0; eligible numeric:=0; discount numeric:=0; shipping numeric:=0;
  code text:=upper(trim(coalesce(p_voucher,''))); eligible_line boolean; used integer; own_used integer;
begin
  if auth.uid() is null then raise exception 'Sign in to calculate your order.'; end if;
  select published into config from public.app_config where id='storefront';
  config:=coalesce(config,'{}');
  if coalesce((config#>>'{features,cashOnDelivery}')::boolean,true)=false then raise exception 'Cash on delivery is currently unavailable.'; end if;
  if coalesce((config#>>'{app,maintenanceMode}')::boolean,false) then raise exception 'The store is temporarily closed for maintenance.'; end if;
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) not between 1 and 100 then raise exception 'Select items to order.'; end if;
  if code<>'' then
    if coalesce((config#>>'{features,coupons}')::boolean,true)=false then raise exception 'Vouchers are currently disabled.'; end if;
    select document into coupon from public.admin_data where collection='coupons' and upper(trim(document->>'code'))=code order by id limit 1;
    if coupon is null then raise exception 'Voucher is not recognized.'; end if;
    if nullif(coupon->>'deletedAt','') is not null or not coalesce((coupon->>'enabled')::boolean,true)
      or (nullif(coupon->>'startsAt','') is not null and (coupon->>'startsAt')::timestamptz>now())
      or (nullif(coupon->>'endsAt','') is not null and (coupon->>'endsAt')::timestamptz<=now()) then raise exception 'This voucher is not active.'; end if;
    if jsonb_array_length(coalesce(coupon->'customerIds','[]'))>0 and not (coupon->'customerIds' ? auth.uid()::text) then raise exception 'This voucher is not available for your account.'; end if;
    if coalesce((coupon->>'firstOrderOnly')::boolean,false) and exists(select 1 from public.orders where user_id=auth.uid() and document->>'status'<>'Cancelled') then raise exception 'This voucher is for first orders only.'; end if;
    -- These eligibility types require verified customer group/birthday data.
    if coalesce((coupon->>'birthdayOnly')::boolean,false) or jsonb_array_length(coalesce(coupon->'customerGroupIds','[]'))>0 then raise exception 'This voucher requires store verification.'; end if;
    select count(*),count(*) filter(where user_id=auth.uid()) into used,own_used from public.orders where upper(document->>'voucher')=code and document->>'status'<>'Cancelled';
    if (coalesce((coupon->>'usageLimit')::int,0)>0 and used>=(coupon->>'usageLimit')::int)
      or (coalesce((coupon->>'perCustomerLimit')::int,0)>0 and own_used>=(coupon->>'perCustomerLimit')::int)
      or (coalesce((coupon->>'oneTime')::boolean,false) and used>0) then raise exception 'This voucher has reached its usage limit.'; end if;
  end if;
  for line in select value from jsonb_array_elements(p_items) loop
    if jsonb_typeof(line->'quantity') is distinct from 'number' or line->>'quantity' !~ '^[0-9]{1,4}$' then raise exception 'Invalid item quantity.'; end if;
    quantity:=(line->>'quantity')::int;
    select * into p from public.products where id=line->>'productId' and active;
    if not found or quantity<1 then raise exception 'A selected product is unavailable.'; end if;
    subtotal:=subtotal+p.price*quantity;
    eligible_line:=coalesce(coupon->>'appliesTo','all')='all'
      or (coupon->>'appliesTo'='products' and coupon->'productIds' ? p.id)
      or (coupon->>'appliesTo'='categories' and exists(select 1 from public.admin_data where collection='products' and id=p.id and coupon->'categoryIds' ? (document->>'categoryId')))
      or (coupon->>'appliesTo'='collections' and exists(select 1 from public.admin_data where collection='collections' and coupon->'collectionIds' ? id and document->'productIds' ? p.id));
    if eligible_line then
      eligible:=eligible+p.price*quantity;
      if coupon->>'type'='bxgy' then
        discount:=discount + floor(quantity::numeric/(greatest(1,coalesce((coupon->>'buyQuantity')::int,1))+greatest(1,coalesce((coupon->>'getQuantity')::int,1))))
          * greatest(1,coalesce((coupon->>'getQuantity')::int,1))*p.price;
      end if;
    end if;
  end loop;
  if subtotal<coalesce((config#>>'{checkout,minimumOrder}')::numeric,0) then raise exception 'The order is below the store minimum.'; end if;
  if coalesce((config#>>'{checkout,maximumOrder}')::numeric,0)>0 and subtotal>(config#>>'{checkout,maximumOrder}')::numeric then raise exception 'The order exceeds the store maximum.'; end if;
  shipping:=greatest(0,coalesce((config#>>'{checkout,defaultShippingFee}')::numeric,0));
  if coalesce((config#>>'{checkout,freeShippingThreshold}')::numeric,0)>0 and subtotal>=(config#>>'{checkout,freeShippingThreshold}')::numeric then shipping:=0; end if;
  if code<>'' then
    if subtotal<coalesce((coupon->>'minPurchase')::numeric,0) then raise exception 'The order is below this voucher minimum.'; end if;
    if eligible<=0 then raise exception 'This voucher does not apply to the selected products.'; end if;
    if coupon->>'type'='percentage' then discount:=round(eligible*least(100,greatest(0,coalesce((coupon->>'value')::numeric,0)))/100,2);
    elsif coupon->>'type'='fixed' then discount:=greatest(0,coalesce((coupon->>'value')::numeric,0));
    elsif coupon->>'type'='free_shipping' then shipping:=0;
    elsif coupon->>'type'<>'bxgy' then raise exception 'Unsupported voucher type.'; end if;
    if coalesce((coupon->>'maxDiscount')::numeric,0)>0 then discount:=least(discount,(coupon->>'maxDiscount')::numeric); end if;
  end if;
  discount:=least(eligible,discount);
  if coalesce((config#>>'{checkout,codLimit}')::numeric,0)>0 and subtotal-discount+shipping>(config#>>'{checkout,codLimit}')::numeric then raise exception 'The order exceeds the cash-on-delivery limit.'; end if;
  return jsonb_build_object('subtotal',subtotal,'discount',discount,'shipping',shipping,'total',subtotal-discount+shipping,'voucher',code);
end $$;
revoke all on function public.quote_order(jsonb,text) from public,anon;
grant execute on function public.quote_order(jsonb,text) to authenticated;

-- Preserve the existing sample promotion as an editable record.
insert into public.admin_data(collection,id,document)
select 'coupons','coupon-gulmeli10',jsonb_build_object('id','coupon-gulmeli10','code','GULMELI10','title','Welcome discount','enabled',true,
  'type','percentage','value',10,'maxDiscount',100,'minPurchase',500,'appliesTo','all','revision',1,'createdAt',now(),'updatedAt',now(),'deletedAt',null)
where not exists(select 1 from public.admin_data where collection='coupons' and upper(document->>'code')='GULMELI10');

create or replace function public.place_order(p_items jsonb, p_profile jsonb, p_voucher text, p_request_id text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  customer uuid := auth.uid();
  result jsonb;
  line jsonb;
  product public.products%rowtype;
  quantity integer;
  lines jsonb := '[]';
  subtotal numeric := 0;
  discount numeric := 0;
  quote jsonb;
  order_id uuid := gen_random_uuid();
begin
  if customer is null then raise exception 'Sign in before placing an order.'; end if;
  if p_request_id is null or length(p_request_id) not between 8 and 150 then raise exception 'Invalid checkout request.'; end if;
  -- Same request after a timeout returns the existing order, without charging stock twice.
  perform pg_advisory_xact_lock(hashtextextended(customer::text || ':' || p_request_id, 0));
  select document into result from public.orders where user_id = customer and request_id = p_request_id;
  if found then return result; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then raise exception 'Select items to order.'; end if;
  if jsonb_array_length(p_items) not between 1 and 100 then raise exception 'Choose between 1 and 100 products.'; end if;
  if p_profile is null or jsonb_typeof(p_profile) <> 'object'
    or coalesce(length(trim(p_profile->>'name')), 0) not between 2 and 150
    or coalesce(length(trim(p_profile->>'address')), 0) not between 8 and 1000
    or coalesce(p_profile->>'phone', '') !~ '^\+?[0-9 -]+$'
    or length(regexp_replace(coalesce(p_profile->>'phone',''), '[^0-9]', '', 'g')) not between 7 and 15
    then raise exception 'Enter a valid name, phone number and delivery address.'; end if;
  if (select count(distinct value->>'productId') from jsonb_array_elements(p_items)) <> jsonb_array_length(p_items)
    then raise exception 'Duplicate or missing products in checkout.'; end if;
  -- Serialize voucher redemption with concurrent checkouts using the same code.
  if trim(coalesce(p_voucher,''))<>'' then perform pg_advisory_xact_lock(hashtextextended('voucher:'||upper(trim(p_voucher)),0)); end if;
  -- Lock products in a consistent order. Any failure rolls the whole transaction back.
  for line in select value from jsonb_array_elements(p_items) order by value->>'productId' loop
    if jsonb_typeof(line->'quantity') is distinct from 'number' or (line->>'quantity') !~ '^[0-9]{1,4}$'
      then raise exception 'Invalid item quantity.'; end if;
    quantity := (line->>'quantity')::integer;
    if quantity < 1 then raise exception 'Invalid item quantity.'; end if;
    select * into product from public.products where id = line->>'productId' and active for update;
    if not found then raise exception 'A product is no longer available.'; end if;
    if product.stock < quantity then raise exception 'Not enough stock for %. Refresh your cart.', product.name; end if;
    update public.products set stock = stock - quantity where id = product.id;
    lines := lines || jsonb_build_array(jsonb_build_object('productId',product.id,'name',product.name,'quantity',quantity,'price',product.price));
    subtotal := subtotal + product.price * quantity;
  end loop;
  quote:=public.quote_order(p_items,p_voucher);
  discount:=(quote->>'discount')::numeric;
  result := jsonb_build_object('id',order_id,'createdAt',now(),'items',lines,'subtotal',subtotal,'discount',discount,'shipping',quote->'shipping','voucher',quote->>'voucher','total',quote->'total',
    'profile',jsonb_build_object('name',trim(p_profile->>'name'),'phone',trim(p_profile->>'phone'),'address',trim(p_profile->>'address'),'avatar',''),
    'status','Placed');
  insert into public.orders(id,user_id,request_id,document) values (order_id,customer,p_request_id,result);
  return result;
end $$;
revoke all on function public.place_order(jsonb,jsonb,text,text) from public, anon;
grant execute on function public.place_order(jsonb,jsonb,text,text) to authenticated;


$migration$; end if; end $stage$;
do $stage$ begin if to_regprocedure('public.send_support_message(text,text,text)') is null then execute $migration$
create or replace function public.send_support_message(p_id text,p_message text,p_subject text default 'Customer care') returns text
language plpgsql security definer set search_path = '' as $$
declare doc jsonb;
begin
  if auth.uid() is null then raise exception 'Sign in to contact the store.'; end if;
  if length(p_id) not between 8 and 100 or length(trim(p_message)) not between 1 and 4000 then raise exception 'Write a message of up to 4000 characters.'; end if;
  perform pg_advisory_xact_lock(hashtextextended('support:'||auth.uid()::text,0));
  select document into doc from public.admin_data where collection='tickets' and id=p_id;
  if found then
    if doc->>'customerId'<>auth.uid()::text then raise exception 'Invalid message reference.'; end if;
    return p_id;
  end if;
  if (select count(*) from public.admin_data where collection='tickets' and document->>'customerId'=auth.uid()::text and updated_at>now()-interval '1 hour')>=20 then raise exception 'Message limit reached. Please try later.'; end if;
  insert into public.admin_data(collection,id,document,actor) values('tickets',p_id,jsonb_build_object(
    'id',p_id,'customerId',auth.uid(),'source','customer-app','subject',left(trim(p_subject),150),
    'category','other','priority','normal','status','open','createdAt',now(),'updatedAt',now(),'revision',1,'deletedAt',null,
    'messages',jsonb_build_array(jsonb_build_object('author','customer','body',trim(p_message),'at',now()))),auth.uid()::text);
  return p_id;
end $$;
revoke all on function public.send_support_message(text,text,text) from public,anon;
grant execute on function public.send_support_message(text,text,text) to authenticated;

create or replace function public.my_support_tickets() returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'subject',document->>'subject','status',document->>'status',
    'messages',document->'messages','updatedAt',updated_at) order by updated_at desc),'[]')
  from public.admin_data where collection='tickets' and document->>'customerId'=auth.uid()::text and nullif(document->>'deletedAt','') is null
$$;
revoke all on function public.my_support_tickets() from public,anon;
grant execute on function public.my_support_tickets() to authenticated;

$migration$; end if; end $stage$;
do $stage$ begin if to_regclass('public.storefront_revision') is null then execute $migration$

-- Public revision signal contains no private dashboard data. It allows shoppers
-- to refresh a published layout immediately without access to admin_data.
create table if not exists public.storefront_revision(id integer primary key check(id=1),updated_at timestamptz not null default now());
alter table public.storefront_revision enable row level security;
grant select on public.storefront_revision to anon,authenticated;
create policy "Read storefront revision" on public.storefront_revision for select to anon,authenticated using(true);
insert into public.storefront_revision(id) values(1) on conflict do nothing;
create or replace function public.signal_storefront_revision() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if coalesce(new.collection,old.collection) in ('homepage_sections','banners','categories','collections','pages','faqs','menus','brands','blog_posts') then
    update public.storefront_revision set updated_at=clock_timestamp() where id=1;
  end if;
  return null;
end $$;
create trigger storefront_content_changed after insert or update or delete on public.admin_data
  for each row execute function public.signal_storefront_revision();
do $$ begin alter publication supabase_realtime add table public.storefront_revision; exception when duplicate_object or undefined_object then null; end $$;

create or replace function public.storefront_content() returns jsonb
language sql stable security definer set search_path='' as $$
with visible as (
  select collection,id,document from public.admin_data
  where nullif(document->>'deletedAt','') is null and (
    (collection in ('banners','categories','collections','pages','faqs','menus','brands','blog_posts')
      and document->>'status' in ('published','active')
      and (nullif(document->>'publishAt','') is null or (document->>'publishAt')::timestamptz<=now())
      and (nullif(document->>'unpublishAt','') is null or (document->>'unpublishAt')::timestamptz>now()))
    or (collection='homepage_sections' and coalesce((document->>'enabled')::boolean,false)
      and (nullif(document->>'startsAt','') is null or (document->>'startsAt')::timestamptz<=now())
      and (nullif(document->>'endsAt','') is null or (document->>'endsAt')::timestamptz>now()))
  )
), safe as (
  select collection,id,(select coalesce(jsonb_object_agg(key,value),'{}') from jsonb_each(document)
    where key=any(array['id','name','title','heading','subheading','subtitle','image','mobileImage','featuredImage','logo','icon',
      'backgroundColor','ctaLabel','ctaLink','categoryId','categoryIds','productId','productIds','bannerIds','collectionId',
      'placement','devices','sortOrder','slug','description','body','html','content','question','answer','status','publishAt','unpublishAt',
      'type','layout','itemLimit','enabled','showOnMobile','showOnDesktop','startsAt','endsAt','videoUrl'])) document
  from visible
  union all select 'homepage_config','layout',jsonb_build_object('configured',exists(select 1 from public.admin_data where collection='homepage_sections' and nullif(document->>'deletedAt','') is null))
)
select coalesce(jsonb_agg(jsonb_build_object('collection',collection,'id',id,'document',document)
  order by coalesce((document->>'sortOrder')::numeric,0),id),'[]') from safe;
$$;
revoke all on function public.storefront_content() from public;
grant execute on function public.storefront_content() to anon,authenticated;

$migration$; end if; end $stage$;
do $stage$ begin if to_regprocedure('public.storefront_product_metadata(jsonb)') is null then execute $migration$

-- Match the actual enabled-based content models and sale-price fields.
create or replace function public.storefront_product_metadata(d jsonb) returns jsonb
language sql immutable set search_path='' as $$
select jsonb_build_object('createdAt',d->>'createdAt','originalPrice',case
  when d ? 'compareAtPrice' or d ? 'salePrice' then
    coalesce(nullif(d->>'compareAtPrice','')::numeric,
      case when nullif(d->>'salePrice','')::numeric < nullif(d->>'price','')::numeric then nullif(d->>'price','')::numeric end)
  else nullif(d->'details'->>'originalPrice','')::numeric end)
$$;
revoke all on function public.storefront_product_metadata(jsonb) from public;
create or replace function public.project_admin_record() returns trigger
language plpgsql security definer set search_path = '' as $$
declare d jsonb; prev jsonb; c text; rid text; photo text; cat text; amount numeric; delta integer;
  live_order public.orders%rowtype; target_status text; item jsonb;
begin
  if tg_op = 'DELETE' then d:=old.document; c:=old.collection; rid:=old.id;
  else d:=new.document; c:=new.collection; rid:=new.id; end if;
  if tg_op = 'UPDATE' then prev:=old.document; else prev:='{}'; end if;
  -- Nested product records are inventory acknowledgements from the server.
  if c='products' and pg_trigger_depth()>1 then return new; end if;
  if c = 'products' then
    if tg_op = 'DELETE' or nullif(d->>'deletedAt','') is not null then
      update public.products set active=false where id=rid;
    else
      select value #>> '{}' into photo from jsonb_array_elements(coalesce(d->'images','[]'))
        where value #>> '{}' like 'https://%' limit 1;
      select document->>'name' into cat from public.admin_data where collection='categories' and id=d->>'categoryId';
      amount:=coalesce(nullif(d->>'salePrice','')::numeric,nullif(d->>'price','')::numeric,0);
      delta:=case when coalesce((d->>'unlimitedStock')::boolean,false) then 99 else coalesce((d->>'stock')::integer,0) end;
      insert into public.products(id,name,price,stock,category,product_group,image_url,details,active)
        values(rid,coalesce(nullif(d->>'name',''),'Unnamed product'),amount,greatest(0,delta),
          coalesce(cat,nullif(d->>'categoryName',''),'General'),
          case when d->>'storefrontGroup' in ('home','offer','choice','recommendation','unavailable') then d->>'storefrontGroup' else 'home' end,
          photo, coalesce(d->'details','{}') || public.storefront_product_metadata(d) || jsonb_build_object('description',d->>'description','brand',d->>'brand','images',coalesce(d->'images','[]')),
          d->>'status'='published')
      on conflict (id) do update set name=excluded.name,price=excluded.price,category=excluded.category,
        product_group=excluded.product_group, image_url=case when d ? 'images' then excluded.image_url else products.image_url end,
        details=products.details || excluded.details,active=excluded.active,
        stock=case when tg_op='UPDATE' then greatest(0,products.stock + delta -
          case when coalesce((prev->>'unlimitedStock')::boolean,false) then 99 else coalesce((prev->>'stock')::integer,0) end)
          else products.stock end;
    end if;
  elsif c='categories' and tg_op <> 'DELETE' then
    update public.products p set category=d->>'name' from public.admin_data a
      where a.collection='products' and a.document->>'categoryId'=rid and p.id=a.id;
  elsif c='media' then
    if tg_op='DELETE' or nullif(d->>'deletedAt','') is not null then
      delete from public.media where id=rid;
    elsif d->>'url' like 'https://%' then
      insert into public.media(id,public_id,url,name,folder,kind,alt,tags,width,height,bytes,note)
      values(rid,nullif(d->>'publicId',''),d->>'url',coalesce(nullif(d->>'name',''),'Photo'),coalesce(d->>'folder','General'),
        coalesce(d->>'kind','image'),coalesce(d->>'alt',''),coalesce(d->'tags','[]'),
        coalesce((d->>'width')::integer,0),coalesce((d->>'height')::integer,0),
        coalesce((d->>'sizeKb')::numeric,0)*1024,coalesce(d->>'note',''))
      on conflict(id) do update set public_id=excluded.public_id,url=excluded.url,name=excluded.name,folder=excluded.folder,
        kind=excluded.kind,alt=excluded.alt,tags=excluded.tags,width=excluded.width,height=excluded.height,bytes=excluded.bytes,note=excluded.note,updated_at=now();
    end if;
  elsif c='orders' and tg_op='UPDATE' and d->>'source'='customer-app' and d->>'status' is distinct from prev->>'status' then
    select * into live_order from public.orders where id::text=rid for update;
    if found then
      target_status:=case lower(d->>'status') when 'cancelled' then 'Cancelled' when 'shipped' then 'Shipped'
        when 'delivered' then 'Delivered' when 'pending' then 'Placed' else initcap(d->>'status') end;
      if live_order.document->>'status' in ('Cancelled','Delivered') and target_status<>live_order.document->>'status' then
        raise exception 'A completed or cancelled order cannot be reopened.';
      end if;
      if target_status='Cancelled' and live_order.document->>'status'<>'Cancelled' then
        if live_order.document->>'status' in ('Shipped','Delivered') then raise exception 'Shipped orders require a return.'; end if;
        for item in select value from jsonb_array_elements(live_order.document->'items') order by value->>'productId' loop
          update public.products set stock=stock+(item->>'quantity')::integer where id=item->>'productId';
          update public.admin_data a set document=a.document || jsonb_build_object(
            'stock',p.stock,'updatedAt',now(),'revision',coalesce((a.document->>'revision')::int,0)+1),updated_at=now()
            from public.products p where a.collection='products' and a.id=p.id and p.id=item->>'productId';
        end loop;
      end if;
      update public.orders set document=jsonb_set(document,'{status}',to_jsonb(target_status)) where id=live_order.id;
    end if;
  end if;
  insert into public.admin_audit(actor,action,resource,record_id) values(auth.uid(),lower(tg_op),c,rid);
  if tg_op='DELETE' then return old; end if; return new;
end $$;
create or replace function public.storefront_content() returns jsonb
language sql stable security definer set search_path='' as $$
with visible as (
  select collection,id,document from public.admin_data
  where nullif(document->>'deletedAt','') is null and (
    (collection in ('banners','collections','pages','faqs','blog_posts')
      and document->>'status' in ('published','active','scheduled')
      and (nullif(document->>'publishAt','') is null or (document->>'publishAt')::timestamptz<=now())
      and (nullif(document->>'unpublishAt','') is null or (document->>'unpublishAt')::timestamptz>now()))
    or (collection in ('categories','brands','menu_items') and coalesce((document->>'enabled')::boolean,true))
    or (collection='homepage_sections' and coalesce((document->>'enabled')::boolean,false)
      and (nullif(document->>'startsAt','') is null or (document->>'startsAt')::timestamptz<=now())
      and (nullif(document->>'endsAt','') is null or (document->>'endsAt')::timestamptz>now()))
  )
), safe as (
  select collection,id,(select coalesce(jsonb_object_agg(key,value),'{}') from jsonb_each(document)
    where key=any(array['id','name','title','heading','subheading','subtitle','image','mobileImage','featuredImage','logo','icon',
      'backgroundColor','ctaLabel','ctaLink','categoryId','categoryIds','productId','productIds','bannerIds','collectionId',
      'placement','devices','sortOrder','slug','description','body','html','content','question','answer','status','publishAt','unpublishAt',
      'label','menu','target','url','parentId','pageId','newTab','type','layout','itemLimit','enabled','showOnMobile','showOnDesktop','startsAt','endsAt','videoUrl'])) document
  from visible
  union all select 'homepage_config','layout',jsonb_build_object('configured',exists(select 1 from public.admin_data where collection='homepage_sections' and nullif(document->>'deletedAt','') is null))
)
select coalesce(jsonb_agg(jsonb_build_object('collection',collection,'id',id,'document',document)
  order by coalesce((document->>'sortOrder')::numeric,0),id),'[]') from safe;
$$;
revoke all on function public.storefront_content() from public;
grant execute on function public.storefront_content() to anon,authenticated;
create or replace function public.signal_storefront_revision() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if coalesce(new.collection,old.collection) in ('homepage_sections','banners','categories','collections','pages','faqs','menu_items','brands','blog_posts') then
    update public.storefront_revision set updated_at=clock_timestamp() where id=1;
  end if;
  return null;
end $$;

update public.products p set details=p.details || public.storefront_product_metadata(a.document) from public.admin_data a where a.collection='products' and a.id=p.id;

$migration$; end if; end $stage$;
commit;
