-- SAMPLE inventory from the original app. Review prices/stock before accepting real orders.
-- Safe to rerun: existing product records are not overwritten.
insert into public.products(id,name,price,stock,category,product_group,image_url,details,sort_order) values
('campaign-3', 'Men 2-in-1 Running Shorts', '499', '99', 'Fashion', 'home', null, '{"discount":"-50%","imageKey":"daraz_app_home_screen-3"}', '0'),
('campaign-4', 'Unidus Long Love', '603', '99', 'Lifestyle', 'home', null, '{"discount":"-4%","imageKey":"daraz_app_home_screen-4"}', '1'),
('campaign-5', 'Men''s Casual Air Fashion Shoes', '1499', '99', 'Fashion', 'home', null, '{"discount":"-25%","imageKey":"daraz_app_home_screen-5"}', '2'),
('campaign-6', 'Jiri Creatine Monohydrate', '854', '99', 'Lifestyle', 'home', null, '{"discount":"-14%","imageKey":"daraz_app_home_screen-6"}', '3'),
('campaign-7', 'Catch Meat Masala', '175', '99', 'Groceries', 'home', null, '{"discount":"HOT","imageKey":"daraz_app_home_screen-7"}', '4'),
('campaign-8', 'Garnier Color Naturals', '517', '99', 'Lifestyle', 'home', null, '{"discount":"-9%","imageKey":"daraz_app_home_screen-8"}', '5'),
('home-0', 'Shopmee Men''s T-shirt Loose Fit Oversized', '399', '99', 'Fashion', 'home', null, '{"discount":"-71%","imageKey":"daraz_app_home_screen-13","rating":"3.9 (31)","sold":201,"gems":0,"fastDelivery":true,"voucher":false}', '6'),
('home-1', 'Men Tactical Belt Quick Release Heavy Duty', '379', '99', 'Fashion', 'home', null, '{"discount":"-24%","imageKey":"daraz_app_home_screen-14","rating":"4.6 (162)","sold":965,"gems":0,"fastDelivery":true,"voucher":true}', '7'),
('home-2', 'Summer Stylish Ice Silk Waffle Polo Shirt', '499', '99', 'Fashion', 'home', null, '{"discount":"-50%","imageKey":"daraz_app_home_screen-15","rating":"4.1 (74)","sold":514,"gems":5,"fastDelivery":false,"voucher":false}', '8'),
('home-3', 'Binay Embroidery Yoga Traditional Loose Pants', '909', '99', 'Fashion', 'home', null, '{"discount":"-19%","imageKey":"daraz_app_home_screen-16","rating":"4.6 (28)","sold":158,"gems":9,"fastDelivery":false,"voucher":false}', '9'),
('home-4', 'Pack of 2 Ice Silk Face UV Shield Protector', '350', '99', 'Fashion', 'home', null, '{"discount":"-46%","imageKey":"daraz_app_home_screen-17","rating":"5 (1)","sold":33,"gems":0,"fastDelivery":false,"voucher":true}', '10'),
('home-5', 'SKMEI 9238 Automatic Mechanical Watch Luxury', '3200', '99', 'Electronics', 'home', null, '{"discount":"-36%","imageKey":"daraz_app_home_screen-18","rating":"5 (1)","gems":32,"fastDelivery":false,"voucher":false}', '11'),
('offer-0', 'Easy Install Tool Screen Protector Glass Tempered For Smart Watches', '484', '99', 'Electronics', 'offer', null, '{"originalPrice":968,"discount":"-50%","imageKey":"daraz_buy_more_save_more_offer_screen-0","badge":"1-5 PCS","rating":"4.0 (2)"}', '12'),
('offer-1', 'Mini Wireless Keyboard and Mouse combo with Bluetooth', '1710', '99', 'Electronics', 'offer', null, '{"originalPrice":3420,"discount":"-50%","imageKey":"daraz_buy_more_save_more_offer_screen-1","badge":"7 COLORS"}', '13'),
('offer-2', 'Elegant Pearl Bracelet Strap Women Luxury Quartz Watch', '822', '99', 'Jewelry', 'offer', null, '{"originalPrice":1644,"discount":"-50%","imageKey":"daraz_buy_more_save_more_offer_screen-2","badge":""}', '14'),
('offer-3', 'Tri-fold Flip Stand Case For Pad X8 Pro / Pad X9 11.5inch 2023', '1555', '99', 'Electronics', 'offer', null, '{"originalPrice":3110,"discount":"-50%","imageKey":"daraz_buy_more_save_more_offer_screen-3","badge":""}', '15'),
('offer-4', 'C Key Portable HiFi Mini Clip USB MP3 Player Micro SD TF Card', '665', '99', 'Electronics', 'offer', null, '{"originalPrice":1330,"discount":"-50%","imageKey":"daraz_buy_more_save_more_offer_screen-4","badge":""}', '16'),
('offer-5', 'New Call Reminder Smart Bracelet Fitness Tracker IP67', '1229', '99', 'Electronics', 'offer', null, '{"originalPrice":2458,"discount":"-50%","imageKey":"daraz_buy_more_save_more_offer_screen-5","badge":""}', '17'),
('offer-6', 'RGB LED Strip Light USB Bluetooth Flexible Lamp Tape with App', '599', '99', 'Electronics', 'offer', null, '{"originalPrice":1090,"discount":"-45%","imageKey":"daraz_buy_more_save_more_offer_screen-6","badge":"16 COLORS"}', '18'),
('offer-7', 'Outdoor UV Protection Summer Sun Visor Cap Empty Top Hat', '399', '99', 'Fashion', 'offer', null, '{"originalPrice":665,"discount":"-40%","imageKey":"daraz_buy_more_save_more_offer_screen-7","badge":"KINIJA"}', '19'),
('dabur', 'Dabur Glucose D 500 Gm', '177', '6', 'Groceries', 'choice', null, '{"originalPrice":210,"illustration":"dabur","brand":"Dabur","store":"Gulmeli Fancy Stores Choice 2"}', '20'),
('didian', 'Didian Compressed High Energy Biscuit (Chocolate Flavor) - 300 gm (1 pack)', '317', '5', 'Groceries', 'choice', null, '{"originalPrice":325,"illustration":"didian","brand":"Didian","store":"Gulmeli Fancy Stores Choice 3"}', '21'),
('horlicks', 'Horlicks Classic malt Jar 1 kg', '842', '99', 'Groceries', 'choice', null, '{"originalPrice":860,"illustration":"horlicks","brand":"Horlicks","store":"Gulmeli Fancy Stores Choice - Unilever"}', '22'),
('gyan', 'Gyan Chiura 800Gm', '110', '0', 'Groceries', 'unavailable', null, '{"illustration":"gyan","brand":"GYAN","store":"ZenFusion Grocer"}', '23'),
('monitor', 'Vartex 24" Frameless Gaming Monitor', '13999', '99', 'Lifestyle', 'recommendation', null, '{"discount":"-26%","illustration":"monitor","rating":"4.7 (109)","sold":359}', '24'),
('restricted', 'Blow Masturvator T...', '2108', '99', 'Lifestyle', 'recommendation', null, '{"discount":"-30%","illustration":"restricted","rating":"4.6 (5)","sold":20}', '25'),
('balaclava', 'Summer Balaclava...', '399', '99', 'Lifestyle', 'recommendation', null, '{"discount":"-53%","illustration":"balaclava","rating":"4.4 (42)","sold":309,"gems":12}', '26'),
('speaker', 'Wireless Portable Bluetooth Speaker', '1050', '99', 'Lifestyle', 'recommendation', null, '{"discount":"-48%","illustration":"speaker","rating":"4.2 (133)","sold":915}', '27'),
('posters', 'Attack On titan Anime Posters', '190', '99', 'Lifestyle', 'recommendation', null, '{"discount":"-16%","illustration":"posters","rating":"4.8 (61)","sold":237,"gems":2}', '28'),
('film', '14-inch Premium Laptop Screen Protector', '81', '99', 'Lifestyle', 'recommendation', null, '{"discount":"-63%","illustration":"film","rating":"3 (20)","sold":152,"gems":4}', '29')
on conflict (id) do nothing;
