import { f, options } from "../fields.ts";
import type { ResourceDefinition } from "../resource.ts";

export const suppliers: ResourceDefinition = {
  key: "suppliers",
  label: "Suppliers",
  singular: "Supplier",
  icon: "industry",
  module: "suppliers",
  labelField: "name",
  fields: [
    f.text("name", "Supplier name", { required: true, width: "half" }),
    f.text("contactPerson", "Contact person", { width: "half" }),
    f.email("email", "Email", { width: "half" }),
    f.phone("phone", "Phone", { width: "half" }),
    f.textarea("address", "Address", { rows: 2 }),
    f.relation("productIds", "Products supplied", "products", {
      multiple: true,
    }),
    f.currency("balance", "Outstanding balance", { width: "half" }),
    f.text("paymentTerms", "Payment terms", {
      width: "half",
      placeholder: "Net 30",
    }),
    f.boolean("enabled", "Active", { defaultValue: true, width: "half" }),
    f.textarea("note", "Notes", { rows: 3 }),
  ],
  columns: [
    { field: "name", label: "Supplier" },
    { field: "contactPerson", label: "Contact", compact: true },
    { field: "phone", label: "Phone", compact: true },
    { field: "balance", label: "Balance", format: "currency" },
    { field: "enabled", label: "Active", format: "boolean" },
  ],
  searchFields: ["name", "contactPerson", "email", "phone"],
  defaultSort: { field: "name", direction: "asc" },
};

export const purchaseOrders: ResourceDefinition = {
  key: "purchase_orders",
  label: "Purchase orders",
  singular: "Purchase order",
  icon: "clipboard-list",
  module: "suppliers",
  labelField: "number",
  description: "Restocking orders, expected delivery and partial receipts.",
  fields: [
    f.text("number", "PO number", { required: true, width: "half" }),
    f.relation("supplierId", "Supplier", "suppliers", {
      required: true,
      width: "half",
    }),
    f.select(
      "status",
      "Status",
      options(
        "draft",
        "ordered",
        "partially_received",
        "received",
        "cancelled",
      ),
      {
        defaultValue: "draft",
        width: "half",
      },
    ),
    f.date("expectedAt", "Expected delivery", { width: "half" }),
    f.date("receivedAt", "Received on", { width: "half" }),
    f.repeater(
      "lines",
      "Items",
      [
        f.text("name", "Product"),
        f.text("sku", "SKU", { width: "third" }),
        f.number("quantity", "Ordered", { width: "third", min: 0 }),
        f.number("receivedQuantity", "Received", { width: "third", min: 0 }),
        f.currency("unitCost", "Unit cost", { width: "third", min: 0 }),
      ],
      {},
    ),
    f.currency("total", "Total cost", { width: "half", min: 0 }),
    f.currency("paid", "Paid", { width: "half", min: 0 }),
    f.boolean("updateStockOnReceive", "Add received quantities to stock", {
      defaultValue: true,
      width: "half",
    }),
    f.textarea("note", "Notes", { rows: 3 }),
  ],
  columns: [
    { field: "number", label: "PO" },
    {
      field: "supplierId",
      label: "Supplier",
      format: "relation",
      resource: "suppliers",
    },
    { field: "status", label: "Status", format: "badge" },
    { field: "total", label: "Total", format: "currency" },
    { field: "expectedAt", label: "Expected", format: "date", compact: true },
  ],
  searchFields: ["number", "note"],
  filters: [
    {
      field: "status",
      label: "Status",
      type: "select",
      options: options(
        "draft",
        "ordered",
        "partially_received",
        "received",
        "cancelled",
      ),
    },
    {
      field: "supplierId",
      label: "Supplier",
      type: "select",
      resource: "suppliers",
    },
  ],
  defaultSort: { field: "createdAt", direction: "desc" },
  features: { duplicate: true },
};

export const expenses: ResourceDefinition = {
  key: "expenses",
  label: "Expenses",
  singular: "Expense",
  icon: "money-bill",
  module: "finance",
  labelField: "title",
  description: "Business costs that feed the net-profit report.",
  fields: [
    f.text("title", "Expense", { required: true, width: "half" }),
    f.select(
      "category",
      "Category",
      options(
        "supplier",
        "advertising",
        "shipping",
        "packaging",
        "salaries",
        "rent",
        "software",
        "other",
      ),
      { required: true, defaultValue: "other", width: "half" },
    ),
    f.currency("amount", "Amount", { required: true, width: "half", min: 0 }),
    f.date("spentAt", "Date", { required: true, width: "half" }),
    f.relation("supplierId", "Supplier", "suppliers", {
      width: "half",
      showIf: (values) => values.category === "supplier",
    }),
    f.text("paymentMethod", "Paid with", { width: "half" }),
    f.image("receipt", "Receipt", { width: "half" }),
    f.boolean("recurring", "Recurring monthly", { width: "half" }),
    f.textarea("note", "Notes", { rows: 2 }),
  ],
  columns: [
    { field: "title", label: "Expense" },
    { field: "category", label: "Category", format: "badge" },
    { field: "amount", label: "Amount", format: "currency" },
    { field: "spentAt", label: "Date", format: "date" },
    {
      field: "recurring",
      label: "Recurring",
      format: "boolean",
      compact: true,
    },
  ],
  searchFields: ["title", "note"],
  filters: [
    {
      field: "category",
      label: "Category",
      type: "select",
      options: options(
        "supplier",
        "advertising",
        "shipping",
        "packaging",
        "salaries",
        "rent",
        "software",
        "other",
      ),
    },
    { field: "spentAt", label: "Date", type: "dateRange" },
    { field: "amount", label: "Amount", type: "numberRange" },
  ],
  defaultSort: { field: "spentAt", direction: "desc" },
};

export const pickupStores: ResourceDefinition = {
  key: "pickup_stores",
  label: "Store locations",
  singular: "Store location",
  icon: "shop",
  module: "settings",
  labelField: "name",
  fields: [
    f.text("name", "Store name", { required: true, width: "half" }),
    f.phone("phone", "Phone", { width: "half" }),
    f.textarea("address", "Address", { rows: 2 }),
    f.text("city", "City", { width: "third" }),
    f.text("district", "District", { width: "third" }),
    f.text("province", "Province", { width: "third" }),
    f.url("mapsUrl", "Google Maps link"),
    f.boolean("pickupAvailable", "Pickup available", {
      defaultValue: true,
      width: "half",
    }),
    f.boolean("enabled", "Open", { defaultValue: true, width: "half" }),
    f.textarea("hours", "Pickup schedule", {
      rows: 3,
      placeholder: "Sun-Fri 10:00-19:00",
    }),
    f.textarea("instructions", "Pickup instructions", { rows: 3 }),
    f.number("sortOrder", "Sort order", { width: "half" }),
  ],
  columns: [
    { field: "name", label: "Store" },
    { field: "city", label: "City", compact: true },
    { field: "pickupAvailable", label: "Pickup", format: "boolean" },
    { field: "enabled", label: "Open", format: "boolean" },
  ],
  searchFields: ["name", "address", "city"],
  defaultSort: { field: "sortOrder", direction: "asc" },
  features: { reorder: true },
};

export const locations: ResourceDefinition = {
  key: "locations",
  label: "Delivery locations",
  singular: "Location",
  icon: "map-location-dot",
  module: "settings",
  labelField: "name",
  description:
    "Countries, provinces, districts, cities and their delivery charges.",
  fields: [
    f.text("name", "Name", { required: true, width: "half" }),
    f.select(
      "level",
      "Level",
      options("country", "province", "district", "city", "area"),
      {
        required: true,
        defaultValue: "city",
        width: "half",
      },
    ),
    f.relation("parentId", "Inside", "locations", { width: "half" }),
    f.text("postalCode", "Postal code", { width: "half" }),
    f.boolean("deliveryAvailable", "Delivery available", {
      defaultValue: true,
      width: "half",
    }),
    f.currency("shippingCharge", "Shipping charge", { width: "half", min: 0 }),
    f.number("etaDays", "Delivery estimate (days)", { width: "half", min: 0 }),
    f.number("sortOrder", "Sort order", { width: "half" }),
  ],
  columns: [
    { field: "name", label: "Location" },
    { field: "level", label: "Level", format: "badge" },
    {
      field: "parentId",
      label: "Inside",
      format: "relation",
      resource: "locations",
      compact: true,
    },
    { field: "shippingCharge", label: "Charge", format: "currency" },
    { field: "deliveryAvailable", label: "Delivers", format: "boolean" },
  ],
  searchFields: ["name", "postalCode"],
  filters: [
    {
      field: "level",
      label: "Level",
      type: "select",
      options: options("country", "province", "district", "city", "area"),
    },
    { field: "deliveryAvailable", label: "Delivers", type: "boolean" },
  ],
  defaultSort: { field: "sortOrder", direction: "asc" },
  features: { reorder: true, duplicate: true },
};

export const translations: ResourceDefinition = {
  key: "translations",
  label: "Translations",
  singular: "Translation",
  icon: "language",
  module: "settings",
  labelField: "key",
  description: "Every storefront label, in every language the store supports.",
  fields: [
    f.text("key", "Key", {
      required: true,
      width: "half",
      placeholder: "cart.addToCart",
    }),
    f.text("group", "Group", { width: "half", defaultValue: "general" }),
    f.text("en", "English", { required: true }),
    f.text("ne", "नेपाली"),
    f.textarea("note", "Where this appears", { rows: 2 }),
  ],
  columns: [
    { field: "key", label: "Key" },
    { field: "group", label: "Group", format: "badge", compact: true },
    { field: "en", label: "English" },
    { field: "ne", label: "Nepali", compact: true },
  ],
  searchFields: ["key", "en", "ne", "group"],
  filters: [{ field: "group", label: "Group", type: "select" }],
  defaultSort: { field: "key", direction: "asc" },
};

export const currencies: ResourceDefinition = {
  key: "currencies",
  label: "Currencies",
  singular: "Currency",
  icon: "coins",
  module: "settings",
  labelField: "code",
  fields: [
    f.text("code", "Code", {
      required: true,
      width: "third",
      placeholder: "NPR",
    }),
    f.text("symbol", "Symbol", {
      required: true,
      width: "third",
      placeholder: "Rs.",
    }),
    f.text("name", "Name", { width: "third" }),
    f.number("rate", "Rate against the base currency", {
      defaultValue: 1,
      width: "half",
      min: 0,
    }),
    f.boolean("base", "Base currency", { width: "half" }),
    f.boolean("enabled", "Enabled", { defaultValue: true, width: "half" }),
  ],
  columns: [
    { field: "code", label: "Code" },
    { field: "symbol", label: "Symbol" },
    { field: "rate", label: "Rate", format: "number" },
    { field: "base", label: "Base", format: "boolean", compact: true },
    { field: "enabled", label: "Enabled", format: "boolean" },
  ],
  searchFields: ["code", "name"],
  defaultSort: { field: "code", direction: "asc" },
};

export const redirects: ResourceDefinition = {
  key: "redirects",
  label: "Redirects",
  singular: "Redirect",
  icon: "arrow-right-arrow-left",
  module: "seo",
  labelField: "from",
  fields: [
    f.text("from", "From path", {
      required: true,
      width: "half",
      placeholder: "/old-product",
    }),
    f.text("to", "To path", {
      required: true,
      width: "half",
      placeholder: "/products/new-product",
    }),
    f.select(
      "code",
      "Type",
      options(["301", "301 permanent"], ["302", "302 temporary"]),
      {
        defaultValue: "301",
        width: "half",
      },
    ),
    f.boolean("enabled", "Enabled", { defaultValue: true, width: "half" }),
    f.readonly("hits", "Hits", { width: "half" }),
  ],
  columns: [
    { field: "from", label: "From" },
    { field: "to", label: "To" },
    { field: "code", label: "Type", format: "badge" },
    { field: "hits", label: "Hits", format: "number", compact: true },
    { field: "enabled", label: "Enabled", format: "boolean" },
  ],
  searchFields: ["from", "to"],
  defaultSort: { field: "createdAt", direction: "desc" },
};

export const searchTerms: ResourceDefinition = {
  key: "search_terms",
  label: "Search management",
  singular: "Search term",
  icon: "magnifying-glass",
  module: "seo",
  labelField: "term",
  description: "Popular searches, no-result searches, synonyms and boosts.",
  fields: [
    f.text("term", "Search term", { required: true, width: "half" }),
    f.number("searches", "Searches", { width: "half", min: 0 }),
    f.number("results", "Results returned", { width: "half", min: 0 }),
    f.tags("synonyms", "Synonyms"),
    f.relation("boostProductIds", "Boost these products", "products", {
      multiple: true,
    }),
    f.relation("hideProductIds", "Hide these products", "products", {
      multiple: true,
    }),
    f.text("redirectTo", "Redirect to", { width: "half" }),
    f.boolean("suggested", "Show as a suggestion", { width: "half" }),
  ],
  columns: [
    { field: "term", label: "Term" },
    { field: "searches", label: "Searches", format: "number" },
    { field: "results", label: "Results", format: "number" },
    {
      field: "suggested",
      label: "Suggested",
      format: "boolean",
      compact: true,
    },
  ],
  searchFields: ["term", "synonyms"],
  filters: [{ field: "results", label: "Results", type: "numberRange" }],
  defaultSort: { field: "searches", direction: "desc" },
};

export const integrations: ResourceDefinition = {
  key: "integrations",
  label: "Integrations",
  singular: "Integration",
  icon: "plug",
  module: "integrations",
  labelField: "name",
  description:
    "Third-party keys and endpoints. Secrets are masked in the dashboard.",
  fields: [
    f.text("name", "Name", { required: true, width: "half" }),
    f.select(
      "category",
      "Category",
      options(
        "analytics",
        "payment",
        "shipping",
        "sms",
        "email",
        "push",
        "storage",
        "maps",
        "captcha",
        "crm",
        "erp",
        "other",
      ),
      { required: true, defaultValue: "other", width: "half" },
    ),
    f.text("provider", "Provider", {
      width: "half",
      placeholder: "Google Analytics, Meta Pixel, Firebase, …",
    }),
    f.boolean("enabled", "Enabled", { defaultValue: false, width: "half" }),
    f.text("publicId", "Public ID / measurement ID", { width: "half" }),
    f.secret("apiKey", "API key", { width: "half" }),
    f.secret("apiSecret", "API secret", { width: "half" }),
    f.url("endpoint", "Endpoint", { width: "half" }),
    f.select("mode", "Mode", options(["test", "Test"], ["live", "Live"]), {
      defaultValue: "test",
      width: "half",
    }),
    f.textarea("note", "Notes", { rows: 2 }),
  ],
  columns: [
    { field: "name", label: "Integration" },
    { field: "category", label: "Category", format: "badge" },
    { field: "mode", label: "Mode", format: "badge", compact: true },
    { field: "enabled", label: "Enabled", format: "boolean" },
  ],
  searchFields: ["name", "provider"],
  filters: [
    {
      field: "category",
      label: "Category",
      type: "select",
      options: options(
        "analytics",
        "payment",
        "shipping",
        "sms",
        "email",
        "push",
        "storage",
        "maps",
        "captcha",
        "crm",
        "erp",
        "other",
      ),
    },
    { field: "enabled", label: "Enabled", type: "boolean" },
  ],
  defaultSort: { field: "category", direction: "asc" },
};

export const webhooks: ResourceDefinition = {
  key: "webhooks",
  label: "Webhooks",
  singular: "Webhook",
  icon: "code-branch",
  module: "integrations",
  labelField: "name",
  fields: [
    f.text("name", "Name", { required: true, width: "half" }),
    f.url("url", "Endpoint URL", { required: true, width: "half" }),
    f.multiselect(
      "events",
      "Events",
      options(
        "order_created",
        "payment_completed",
        "order_shipped",
        "order_delivered",
        "refund",
        "customer_created",
        "product_updated",
      ),
      { defaultValue: ["order_created"] },
    ),
    f.secret("secret", "Signing secret", { width: "half" }),
    f.number("retries", "Retry attempts", {
      defaultValue: 3,
      width: "half",
      min: 0,
    }),
    f.boolean("enabled", "Enabled", { defaultValue: true, width: "half" }),
    f.readonly("lastStatus", "Last delivery", { width: "half" }),
  ],
  columns: [
    { field: "name", label: "Webhook" },
    { field: "url", label: "URL", compact: true },
    { field: "events", label: "Events", format: "tags", compact: true },
    { field: "lastStatus", label: "Last delivery", format: "badge" },
    { field: "enabled", label: "Enabled", format: "boolean" },
  ],
  searchFields: ["name", "url"],
};

export const webhookLogs: ResourceDefinition = {
  key: "webhook_logs",
  label: "Webhook log",
  singular: "Delivery",
  icon: "list-check",
  module: "integrations",
  labelField: "event",
  fields: [
    f.relation("webhookId", "Webhook", "webhooks", { width: "half" }),
    f.text("event", "Event", { width: "half" }),
    f.select("status", "Status", options("delivered", "failed", "retrying"), {
      width: "half",
    }),
    f.number("responseCode", "Response code", { width: "half" }),
    f.number("attempts", "Attempts", { width: "half", min: 0 }),
    f.textarea("payload", "Payload", { rows: 5 }),
    f.textarea("error", "Error", { rows: 2 }),
  ],
  columns: [
    { field: "createdAt", label: "When", format: "datetime" },
    {
      field: "webhookId",
      label: "Webhook",
      format: "relation",
      resource: "webhooks",
    },
    { field: "event", label: "Event", format: "badge" },
    { field: "status", label: "Status", format: "badge" },
    { field: "responseCode", label: "Code", format: "number", compact: true },
  ],
  searchFields: ["event", "error"],
  filters: [
    {
      field: "status",
      label: "Status",
      type: "select",
      options: options("delivered", "failed", "retrying"),
    },
  ],
  defaultSort: { field: "createdAt", direction: "desc" },
  features: { create: false, edit: false, revisions: false },
};

export const automations: ResourceDefinition = {
  key: "automations",
  label: "Automation rules",
  singular: "Automation",
  icon: "robot",
  module: "automation",
  labelField: "name",
  description: "When something happens, do something - without a developer.",
  fields: [
    f.text("name", "Rule name", { required: true, width: "half" }),
    f.boolean("enabled", "Enabled", { defaultValue: true, width: "half" }),
    f.select(
      "trigger",
      "When",
      options(
        ["stock_below", "Stock falls below a threshold"],
        ["order_placed", "An order is placed"],
        ["order_shipped", "An order is shipped"],
        ["order_delivered", "An order is delivered"],
        ["cart_abandoned", "A cart is abandoned"],
        ["back_in_stock", "A product is back in stock"],
        ["customer_spend", "A customer's lifetime spend passes an amount"],
        ["order_total_above", "An order total passes an amount"],
        ["payment_failed", "A payment fails"],
        ["refund_approved", "A refund is approved"],
        ["review_created", "A review is submitted"],
      ),
      { required: true, defaultValue: "order_placed", width: "half" },
    ),
    f.number("threshold", "Threshold", {
      width: "half",
      help: "Stock level or amount, depending on the trigger.",
    }),
    f.select(
      "action",
      "Then",
      options(
        ["notify_admin", "Notify the admin team"],
        ["email_customer", "Email the customer"],
        ["push_customer", "Send the customer a push notification"],
        ["sms_customer", "Send the customer an SMS"],
        ["tag_customer", "Tag the customer"],
        ["assign_vip", "Make the customer VIP"],
        ["free_shipping", "Give free shipping"],
        ["create_ticket", "Open a support ticket"],
        ["webhook", "Call a webhook"],
      ),
      { required: true, defaultValue: "notify_admin", width: "half" },
    ),
    f.text("actionValue", "Action detail", {
      width: "half",
      help: "Template name, tag, or webhook name, depending on the action.",
    }),
    f.number("delayMinutes", "Delay before acting (minutes)", {
      width: "half",
      min: 0,
    }),
    f.textarea("description", "Description", { rows: 2 }),
    f.readonly("lastRunAt", "Last run", { width: "half" }),
    f.readonly("runCount", "Times run", { width: "half" }),
  ],
  columns: [
    { field: "name", label: "Rule" },
    { field: "trigger", label: "When", format: "badge" },
    { field: "action", label: "Then", format: "badge" },
    { field: "runCount", label: "Runs", format: "number", compact: true },
    { field: "enabled", label: "Enabled", format: "boolean" },
  ],
  searchFields: ["name", "description"],
  features: { duplicate: true },
};

export const errorLogs: ResourceDefinition = {
  key: "error_logs",
  label: "Error log",
  singular: "Error",
  icon: "triangle-exclamation",
  module: "system",
  labelField: "message",
  description:
    "API, payment, email, SMS, push, webhook and background-job failures.",
  fields: [
    f.select(
      "source",
      "Source",
      options(
        "api",
        "payment",
        "email",
        "sms",
        "push",
        "webhook",
        "server",
        "job",
      ),
      { width: "half" },
    ),
    f.select(
      "severity",
      "Severity",
      options("info", "warning", "error", "critical"),
      { width: "half" },
    ),
    f.text("message", "Message", { required: true }),
    f.textarea("detail", "Detail", { rows: 5 }),
    f.boolean("resolved", "Resolved", { width: "half" }),
  ],
  columns: [
    { field: "createdAt", label: "When", format: "datetime" },
    { field: "source", label: "Source", format: "badge" },
    { field: "severity", label: "Severity", format: "badge" },
    { field: "message", label: "Message" },
    { field: "resolved", label: "Resolved", format: "boolean", compact: true },
  ],
  searchFields: ["message", "detail"],
  filters: [
    {
      field: "source",
      label: "Source",
      type: "select",
      options: options(
        "api",
        "payment",
        "email",
        "sms",
        "push",
        "webhook",
        "server",
        "job",
      ),
    },
    {
      field: "severity",
      label: "Severity",
      type: "select",
      options: options("info", "warning", "error", "critical"),
    },
    { field: "resolved", label: "Resolved", type: "boolean" },
  ],
  defaultSort: { field: "createdAt", direction: "desc" },
  features: { create: false, revisions: false },
};

export const backups: ResourceDefinition = {
  key: "backups",
  label: "Backups",
  singular: "Backup",
  icon: "database",
  module: "system",
  labelField: "name",
  fields: [
    f.text("name", "Backup name", { required: true, width: "half" }),
    f.select(
      "kind",
      "Type",
      options(["manual", "Manual"], ["automatic", "Automatic"]),
      {
        defaultValue: "manual",
        width: "half",
      },
    ),
    f.select("status", "Status", options("complete", "running", "failed"), {
      defaultValue: "complete",
      width: "half",
    }),
    f.number("sizeKb", "Size (KB)", { width: "half", min: 0 }),
    f.number("records", "Records", { width: "half", min: 0 }),
    f.textarea("note", "Note", { rows: 2 }),
  ],
  columns: [
    { field: "name", label: "Backup" },
    { field: "kind", label: "Type", format: "badge" },
    { field: "status", label: "Status", format: "badge" },
    { field: "sizeKb", label: "KB", format: "number", compact: true },
    { field: "createdAt", label: "Taken", format: "datetime" },
  ],
  searchFields: ["name", "note"],
  defaultSort: { field: "createdAt", direction: "desc" },
  features: { revisions: false },
};

export const dataRequests: ResourceDefinition = {
  key: "data_requests",
  label: "Data requests",
  singular: "Data request",
  icon: "user-lock",
  module: "system",
  labelField: "email",
  description: "Customer data-export and data-deletion requests.",
  fields: [
    f.relation("customerId", "Customer", "customers", { width: "half" }),
    f.email("email", "Email", { required: true, width: "half" }),
    f.select(
      "kind",
      "Request",
      options(["export", "Data export"], ["delete", "Data deletion"]),
      {
        required: true,
        width: "half",
      },
    ),
    f.select(
      "status",
      "Status",
      options("received", "in_progress", "completed", "rejected"),
      {
        defaultValue: "received",
        width: "half",
      },
    ),
    f.date("dueBy", "Due by", { width: "half" }),
    f.textarea("note", "Note", { rows: 3 }),
  ],
  columns: [
    { field: "email", label: "Customer" },
    { field: "kind", label: "Request", format: "badge" },
    { field: "status", label: "Status", format: "badge" },
    { field: "dueBy", label: "Due", format: "date" },
  ],
  searchFields: ["email", "note"],
  defaultSort: { field: "createdAt", direction: "desc" },
};

export const operationsResources = [
  suppliers,
  purchaseOrders,
  expenses,
  pickupStores,
  locations,
  translations,
  currencies,
  redirects,
  searchTerms,
  integrations,
  webhooks,
  webhookLogs,
  automations,
  errorLogs,
  backups,
  dataRequests,
];
