// Upload existing artwork and sourced product photographs to this store's Cloudinary.
// Writes a resumable public manifest and non-destructive SQL; never prints secrets.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { appEnv, serverEnv, mobileRoot } from "./backend-env.mjs";
import path from "node:path";
const cloud = serverEnv.CLOUDINARY_CLOUD_NAME;
if (
  !cloud ||
  cloud !== appEnv.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME ||
  !serverEnv.CLOUDINARY_API_KEY ||
  !serverEnv.CLOUDINARY_API_SECRET
)
  throw Error("Configure matching Cloudinary settings first.");
const output = path.join(mobileRoot, "src/data/hosted-media.json");
const manifest = existsSync(output)
  ? JSON.parse(readFileSync(output, "utf8"))
  : {};
const sourceCode = readFileSync(
  path.join(mobileRoot, "src/data/stitch-images.ts"),
  "utf8",
);
const assets = [
  ...sourceCode.matchAll(/"([^"]+)": require\("([^\"]+)"\)/g),
].map((m) => ({
  id: m[1],
  file: path.resolve(mobileRoot, "src/data", m[2]),
  source: "Original project artwork",
  illustrative: false,
}));
assets.push(
  ...JSON.parse(
    readFileSync(new URL("./photo-sources.json", import.meta.url), "utf8"),
  ),
);
mkdirSync(path.join(mobileRoot, "assets/product-photos"), { recursive: true });
let failures = 0;
for (const asset of assets) {
  if (manifest[asset.id]?.cloud === cloud) continue;
  try {
    let bytes;
    if (asset.file) bytes = readFileSync(asset.file);
    else {
      const response = await fetch(asset.url, {
        signal: AbortSignal.timeout(30000),
      });
      if (
        !response.ok ||
        !response.headers.get("content-type")?.startsWith("image/")
      )
        throw Error("Source image unavailable");
      bytes = Buffer.from(await response.arrayBuffer());
      if (bytes.length > 10_000_000) throw Error("Source image too large");
      writeFileSync(
        path.join(mobileRoot, "assets/product-photos", asset.id + ".jpg"),
        bytes,
      );
    }
    const params = {
      public_id: `gulmeli/catalog/${asset.id}`,
      overwrite: "false",
      timestamp: String(Math.floor(Date.now() / 1000)),
    };
    const signature = createHash("sha1")
      .update(
        Object.keys(params)
          .sort()
          .map((k) => `${k}=${params[k]}`)
          .join("&") + serverEnv.CLOUDINARY_API_SECRET,
      )
      .digest("hex");
    const form = new FormData();
    for (const [key, value] of Object.entries(params)) form.append(key, value);
    form.append("api_key", serverEnv.CLOUDINARY_API_KEY);
    form.append("signature", signature);
    form.append("file", new Blob([bytes]), asset.id + ".jpg");
    const response = await fetch(
      `https://api.cloudinary.com/v1_1/${cloud}/image/upload`,
      { method: "POST", body: form, signal: AbortSignal.timeout(60000) },
    );
    const uploaded = await response.json();
    if (!response.ok || !uploaded.secure_url)
      throw Error(`Cloudinary upload failed (${response.status})`);
    manifest[asset.id] = {
      cloud,
      url: uploaded.secure_url,
      publicId: uploaded.public_id,
      width: uploaded.width,
      height: uploaded.height,
      bytes: uploaded.bytes,
      source: asset.source,
      illustrative: asset.illustrative ?? false,
    };
    writeFileSync(output, JSON.stringify(manifest, null, 2) + "\n");
    console.log("Uploaded:", asset.id);
  } catch (error) {
    failures++;
    console.error(asset.id + ": " + error.message);
  }
}
const sqlString = (value) =>
  "'" + JSON.stringify(value).replaceAll("'", "''") + "'::jsonb";
const rows = Object.entries(manifest).map(([id, m]) => {
  const aliases = [id];
  const home = id.match(/^daraz_app_home_screen-(\d+)$/);
  const offer = id.match(/^daraz_buy_more_save_more_offer_screen-(\d+)$/);
  if (home) {
    const index = Number(home[1]);
    if (index >= 13 && index <= 18) aliases.push(`home-${index - 13}`);
    if (index >= 3 && index <= 8) aliases.push(`campaign-${index}`);
  }
  if (offer) aliases.push(`offer-${offer[1]}`);
  return {
    id,
    ...m,
    productIds: aliases.flatMap((alias) => [alias, `prod_${alias}`]),
  };
});
writeFileSync(
  path.join(mobileRoot, "supabase/catalog-photos.sql"),
  `-- Generated by backend:photos. Only fills missing images; preserves prices and stock.\nbegin;\n` +
    `do $$ declare photo jsonb; p record; doc jsonb; begin\nfor photo in select value from jsonb_array_elements(${sqlString(rows)}) loop\n` +
    `for p in select * from public.products where ((photo->'productIds') ? id or details->>'imageKey'=photo->>'id') and image_url is null loop\n` +
    `update public.products set image_url=photo->>'url',details=details||jsonb_build_object('images',jsonb_build_array(photo->>'url'),'imageIllustrative',photo->'illustrative') where id=p.id;\n` +
    `update public.admin_data set document=document||jsonb_build_object('images',jsonb_build_array(photo->>'url')) where collection='products' and id=p.id and (not document ? 'images' or document->'images'='[]');\nend loop;\n` +
    `doc:=jsonb_build_object('id','photo-'||(photo->>'id'),'name',photo->>'id','url',photo->>'url','publicId',photo->>'publicId','kind','image','folder','Catalog','width',photo->'width','height',photo->'height','sizeKb',(photo->>'bytes')::numeric/1024,'alt',photo->>'id','note',photo->>'source','revision',1,'createdAt',now(),'updatedAt',now(),'deletedAt',null);\n` +
    `insert into public.admin_data(collection,id,document) values('media',doc->>'id',doc) on conflict do nothing;\nend loop;end $$;\ncommit;\n`,
);
console.log(
  `Hosted assets: ${Object.keys(manifest).length}. SQL: supabase/catalog-photos.sql. Source failures: ${failures}.`,
);
process.exitCode = failures ? 1 : 0;
