import { readFileSync, writeFileSync } from "node:fs";
const migrations = [
  ["202609130001_store.sql", "to_regclass('public.products') is null"],
  [
    "202609140001_admin_config.sql",
    "to_regclass('public.admin_members') is null",
  ],
  ["202609140002_media_sync.sql", "to_regclass('public.admin_data') is null"],
  [
    "202609140003_push_tokens.sql",
    "to_regclass('public.device_tokens') is null",
  ],
  [
    "202609150001_live_backend.sql",
    "to_regprocedure('public.save_admin_changes(jsonb)') is null",
  ],
  [
    "202609150002_checkout_rules.sql",
    "to_regprocedure('public.quote_order(jsonb,text)') is null",
  ],
  [
    "202609150003_customer_support.sql",
    "to_regprocedure('public.send_support_message(text,text,text)') is null",
  ],
  ["202609160001_storefront_appearance.sql", "to_regclass('public.storefront_revision') is null"],
];
migrations.push(["202609160002_storefront_fields.sql", "to_regprocedure('public.storefront_product_metadata(jsonb)') is null"]);
let sql =
  "-- Generated by npm run backend:prepare. Applies only missing schema stages.\n-- No catalog reset, no automatic admin claim, no credentials.\nbegin;\n";
for (const [name, condition] of migrations) {
  const source = readFileSync(
    new URL("../supabase/migrations/" + name, import.meta.url),
    "utf8",
  )
    .replace(/^begin;\s*$/gm, "")
    .replace(/^commit;\s*$/gm, "");
  sql += `do $stage$ begin if ${condition} then execute $migration$\n${source}\n$migration$; end if; end $stage$;\n`;
}
sql += "commit;\n";
writeFileSync(new URL("../supabase/deploy.sql", import.meta.url), sql);
console.log("Prepared supabase/deploy.sql for the configured project.");
